{% set name = "vim" %}
{% set version = "8.2.4627" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vim/vim/archive/v{{ version }}.tar.gz
  sha256: c9572e0eaff7a2a0f6529b586247d75f8b42d55e6cd4260b82cb89c7482c961c

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - perl
    - ncurses  # [not win]
    - gettext
  run:
    - python
    - perl
    - ncurses  # [not win]
    - gettext

test:
  commands:
    - vim --version | grep {{ version }}

about:
  home: https://www.vim.org/
  # vi(m) is licensed as charity-ware
  license: Vim
  license_file: runtime/doc/uganda.txt
  summary: Vim is a greatly improved version of the good old UNIX editor Vi
  dev_url: https://github.com/vim/vim
  doc_url: https://www.vim.org/docs.php

extra:
  recipe-maintainers:
    - mariusvniekerk
    - scopatz
    - asford
    - matthiasdiener
