{% set name = "vim" %}
{% set version = "8.1.1348" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vim/vim/archive/v{{ version }}.tar.gz
  sha256: b37ff786b256b52a3e91e8bec5b1008e9656bad6ca7552228e8373430aefa26f

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - ncurses
  run:
    - python
    - ncurses

test:
  commands:
    - vim --version

about:
  home: https://www.vim.org/
  # vi(m) is licensed as charity-ware
  license: OTHER
  license_file: runtime/doc/uganda.txt
  summary: 'Vim is a greatly improved version of the good old UNIX editor Vi'
  dev_url: https://github.com/vim/vim

extra:
  recipe-maintainers:
    - mariusvniekerk
    - scopatz
