{% set name = "vim" %}
{% set version = "8.2.4960" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vim/vim/archive/v{{ version }}.tar.gz
  sha256: 43b78b91855ab1685911a9412159793a2c1f3817218c7c6ead8572f076f0629c

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - perl     # [not win]
    - ncurses  # [not win]
    - gettext
  run:
    - python
    - perl     # [not win]
    - ncurses  # [not win]
    - gettext

test:
  commands:
    - vim --version
    - if not exist %LIBRARY_BIN%/vim.exe exit 1  # [win]
    - test -f $PREFIX/bin/vim                    # [not win]

about:
  home: https://www.vim.org/
  # vi(m) is licensed as charity-ware
  license: Vim
  license_file: runtime/doc/uganda.txt
  summary: Vim is a greatly improved version of the good old UNIX editor Vi
  dev_url: https://github.com/vim/vim
  doc_url: https://www.vim.org/docs.php

extra:
  recipe-maintainers:
    - mariusvniekerk
    - scopatz
    - asford
    - matthiasdiener
