{% set name = "vim" %}
{% set version = "9.1.1214" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vim/vim/archive/v{{ version }}.tar.gz
  sha256: e087423f3d5348ce0284c97632a81edd28aefd0b2a25061e1a61a94b1d10cbae

build:
  number: 0
  skip: true  # [win and python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - perl     # [not win]
    - ncurses  # [not win]
    - gettext
    - xorg-libx11     # [linux]
    - xorg-libxt      # [linux]
    - xorg-xorgproto  # [linux]
  run:
    - python
    - perl     # [not win]
    - ncurses  # [not win]
    - gettext
    - xorg-libx11     # [linux]
    - xorg-libxt      # [linux]
    - xorg-xorgproto  # [linux]

test:
  commands:
    - vim --version
    - if not exist %LIBRARY_BIN%/vim.exe exit 1  # [win]
    - test -f $PREFIX/bin/vim                    # [not win]

about:
  home: https://www.vim.org/
  # vi(m) is licensed as charity-ware
  license: Vim
  license_file: runtime/doc/uganda.txt
  summary: Vim is a greatly improved version of the good old UNIX editor Vi
  dev_url: https://github.com/vim/vim
  doc_url: https://www.vim.org/docs.php

extra:
  recipe-maintainers:
    - blmaier
    - mariusvniekerk
    - scopatz
    - asford
    - matthiasdiener
