{% set name = "vim" %}
{% set version = "8.2.2549" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vim/vim/archive/v{{ version }}.tar.gz
  sha256: e6438a6161e734615a8e3db55d138601f6322e0b3efd6f5b7f8d3e54603f95bd

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - ncurses
  run:
    - python
    - ncurses

test:
  commands:
    - vim --version

about:
  home: https://www.vim.org/
  # vi(m) is licensed as charity-ware
  license: OTHER
  license_file: runtime/doc/uganda.txt
  summary: Vim is a greatly improved version of the good old UNIX editor Vi
  dev_url: https://github.com/vim/vim

extra:
  recipe-maintainers:
    - mariusvniekerk
    - scopatz
    - asford
