{% set name = "vim" %}
{% set version = "8.2.2316" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vim/vim/archive/v{{ version }}.tar.gz
  sha256: 41fd4a11dc3f590030b3dd2b2125c977aecc198a53088b182bb3bbfe700032e7

build:
  number: 1
  skip: True  # [py < 36 or python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_{{ target_platform }}  # [win]
    - make
  host:
    - python  # [not win]
    - ncurses  # [not win]
  run:
    - python  # [not win]
    - ncurses  # [not win]

test:
  commands:
    - vim --version

about:
  home: https://www.vim.org/
  # vi(m) is licensed as charity-ware
  license: OTHER
  license_file: runtime/doc/uganda.txt
  summary: Vim is a greatly improved version of the good old UNIX editor Vi
  dev_url: https://github.com/vim/vim

extra:
  recipe-maintainers:
    - mariusvniekerk
    - scopatz
    - asford
    
