{% set name = "vim" %}
{% set version = "8.2.2271" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vim/vim/archive/v{{ version }}.tar.gz
  sha256: 6cb0c0bfdf855bad3af1a8c06ced5e67449d69cdec1974ae54f3b4679b146020

build:
  skip: true  # [(win and vc<14)]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - ncurses # [not win]
  run:
    - python
    - ncurses # [not win]

test:
  commands:
    - vim --version

about:
  home: https://www.vim.org/
  # vi(m) is licensed as charity-ware
  license: OTHER
  license_file: runtime/doc/uganda.txt
  summary: Vim is a greatly improved version of the good old UNIX editor Vi
  dev_url: https://github.com/vim/vim

extra:
  recipe-maintainers:
    - mariusvniekerk
    - scopatz
    - asford
